use_frameworks!

platform :ios, '8.0'

target 'MTBeaconPlus_Example' do
  pod 'MTBeaconPlus', :path => '../'

  target 'MTBeaconPlus_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
